site_name: Pretronic Docs Platform
site_description: Build amazing things with Pretronic projects.
site_url: https://docs.pretronic.net/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  extra_css:
    - stylesheets/bootstrap-grid.min.css
    - stylesheets/style.css
  icon:
    repo: fontawesome/brands/github
  logo: https://content.pretronic.net/brand/logo/pretronic-blue.png
  favicon: https://content.pretronic.net/brand/logo/pretronic-blue.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - meta
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      clickable_checkbox: false
  - toc:
      permalink: true
      toc_depth: 3

google_analytics:
  - G-FR8HP348XX
  - auto

plugins:
  - search
  - git-revision-date

extra_css:
  - stylesheets/bootstrap-grid.min.css
  - stylesheets/style.css
  - stylesheets/docs-style.css


edit_uri: https://github.com/Pretronic/Pretronic-Documentation/edit/main/projects/home/docs/
disableRepo: true

